name = "finterp"
version = "1.3.0"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2016-2024, Jacob Williams"
license = "BSD"
description = "Modern Fortran Multidimensional Linear Interpolation"
homepage = "https://github.com/jacobwilliams/finterp"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = true
auto-examples = true
auto-tests = true